export const PAGES_LIST_REQUEST = 'PAGES_LIST_REQUEST'
export const PAGES_LIST_SUCCESS = 'PAGES_LIST_SUCCESS'
export const PAGES_LIST_FAIL = 'PAGES_LIST_FAIL'


export const PAGES_DETAILS_REQUEST = 'PAGES_DETAILS_REQUEST'
export const PAGES_DETAILS_SUCCESS = 'PAGES_DETAILS_SUCCESS'
export const PAGES_DETAILS_FAIL = 'PAGES_DETAILS_FAIL'