//my constants for redux reducers


export const PAGES_LIST_REQUEST = 'PAGES_LIST_REQUEST'
export const PAGES_LIST_SUCCESS = 'PAGES_LIST_SUCCESS'
export const PAGES_LIST_FAIL = 'PAGES_LIST_FAIL'


export const PAGES_DETAILS_REQUEST = 'PAGES_DETAILS_REQUEST'
export const PAGES_DETAILS_SUCCESS = 'PAGES_DETAILS_SUCCESS'
export const PAGES_DETAILS_FAIL = 'PAGES_DETAILS_FAIL'

export const PAGES_DELETE_REQUEST = 'PAGES_DELETE_REQUEST'
export const PAGES_DELETE_SUCCESS = 'PAGES_DELETE_SUCCESS'
export const PAGES_DELETE_FAIL = 'PAGES_DELETE_FAIL'

export const PAGES_CREATE_REQUEST = 'PAGES_CREATE_REQUEST'
export const PAGES_CREATE_SUCCESS = 'PAGES_CREATE_SUCCESS'
export const PAGES_CREATE_FAIL = 'PAGES_CREATE_FAIL'
export const PAGES_CREATE_RESET = 'PAGES_CREATE_RESET'



export const PAGES_UPDATE_REQUEST = 'PAGES_UPDATE_REQUEST'
export const PAGES_UPDATE_SUCCESS = 'PAGES_UPDATE_SUCCESS'
export const PAGES_UPDATE_FAIL = 'PAGES_UPDATE_FAIL'
export const PAGES_UPDATE_RESET = 'PAGES_UPDATE_RESET'